apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ .Chart.Name }}-daemonset
  namespace: kube-system
  labels:
    k8s-app: {{ .Chart.Name }}-logger
    version: {{ .Chart.Version }}
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    matchLabels:
      k8s-app: {{ .Chart.Name }}-logger
  template:
    metadata:
      annotations:
        iam.amazonaws.com/role: fluentd
      labels:
        k8s-app: {{ .Chart.Name }}-logger
        version: {{ .Chart.AppVersion }}
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: fluentd
        image: {{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 24224
          protocol: TCP
          name: fluentd
        - containerPort: 9880
          protocol: TCP
          name: http
        - containerPort: 5140
          protocol: UDP
          name: syslog
        envFrom:
        - secretRef:
           name: {{ .Chart.Name }}-account-secrets
        resources:
          limits:
            memory: 400Mi
          requests:
            cpu: 100m
            memory: 400Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: fluentd-config
          mountPath: /fluentd/etc/fluent.conf
          subPath: fluent.conf
        - name: fluentd-config
          mountPath: /fluentd/etc/conf/child/kubernetes.conf
          subPath: kubernetes.conf
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: fluentd-config
        configMap:
          name: {{ .Chart.Name }}-configs
      serviceAccount: {{ .Chart.Name }}-service-account
      serviceAccountName: {{ .Chart.Name }}-service-account
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule